Graal native-image on Windows does not like opt
Graal's native-image's --native-image-info opt was causing my build
on Windows to fail with an:
java.lang.IllegalArgumentException: 'other' has different root

Worked fine on linux and macOS